/* Filter Actions */
// export const TOGGLE_FILTER = 'TOGGLE_FILTER';
// export const CLEAR_FILTERS = 'CLEAR_FILTERS';

/* Result Actions */
export const SET_SEARCH_QUERY = 'SET_SEARCH_QUERY';
export const RELOADING_SAME_QUERY = 'RELOADING_SAME_QUERY';
export const LOADING_RESULTS = 'LOADING_RESULTS';
export const FETCH_NEW_QUERY = 'FETCH_NEW_QUERY';
export const FETCH_WITH_FILTERS = 'FETCH_WITH_FILTERS';
export const UPDATE_PAGE_NUMBER = 'UPDATE_PAGE_NUMBER';
export const FETCH_NEW_PAGE = 'FETCH_NEW_PAGE';
export const UPDATE_SOME_AGGREGATIONS = 'UPDATE_SOME_AGGREGATIONS';
export const UPDATE_ALL_AGGREGATIONS = "UPDATE_ALL_AGGREGATIONS";
